config { 
    type: "table"
}
SELECT
    a.SalesOrderID
    , b.SalesOrderDetailID
    , a.OrderDate
    , a.CustomerID
    , a.TerritoryID
    , b.ProductID
    , b.OrderQty
    , b.UnitPrice
    , b.UnitPriceDiscount
    , b.LineTotal
    , a.TotalDue
FROM
    ${ref("adventureworks", "SalesOrderHeader")} a
INNER JOIN
        ${ref("adventureworks", "SalesOrderDetail")} b
ON
    a.SalesOrderID = b.SalesOrderID